// Code generated by the conjuretypescriptcli generator. DO NOT EDIT.
// To update this file, run the generator in ir-gen-cli-bundler/conjuretypescriptcli/generator.
package asset

const Version = "5.18.0"
