// Copyright (c) 2018 Palantir Technologies. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package conjureplugin

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/palantir/conjure-go/v6/conjure"
	conjurego "github.com/palantir/conjure-go/v6/conjure"
	"github.com/palantir/conjure-go/v6/conjure-api/conjure/spec"
	"github.com/pkg/errors"
)

const indentLen = 2

func Run(params ConjureProjectParams, verify bool, projectDir string, stdout io.Writer) error {
	var verifyFailedIndex []int
	verifyFailedErrors := make(map[int]string)
	verifyFailedFn := func(name int, errStr string) {
		verifyFailedIndex = append(verifyFailedIndex, name)
		verifyFailedErrors[name] = errStr
	}

	k := 0
	for _, currParam := range params.OrderedParams() {
		outputDir := currParam.OutputDir
		conjureDef, err := conjureDefinitionFromParam(currParam)
		if err != nil {
			return err
		}

		outputConf := conjure.OutputConfiguration{
			OutputDir:            path.Join(projectDir, outputDir),
			GenerateServer:       currParam.Server,
			GenerateCLI:          currParam.CLI,
			GenerateFuncsVisitor: currParam.AcceptFuncs,
		}
		if verify {
			diff, err := diffOnDisk(conjureDef, projectDir, outputConf)
			if err != nil {
				return err
			}
			if len(diff.Diffs) > 0 {
				verifyFailedFn(k, diff.String())
			}
		} else {
			// V2: Clean up old generated files before regenerating (unless skip-delete-generated-files is set)
			if !currParam.SkipDeleteGeneratedFiles {
				if err := cleanupGeneratedFiles(path.Join(projectDir, outputDir)); err != nil {
					return errors.Wrapf(err, "failed to cleanup generated files in %s", outputDir)
				}
			}

			if err := conjure.Generate(conjureDef, outputConf); err != nil {
				return err
			}
		}
		k++
	}

	if verify && len(verifyFailedIndex) > 0 {
		_, _ = fmt.Fprintf(stdout, "Conjure output differs from what currently exists: %v\n", verifyFailedIndex)
		for _, currKey := range verifyFailedIndex {
			_, _ = fmt.Fprintf(stdout, "%s%d:\n", strings.Repeat(" ", indentLen), currKey)
			for _, currErrLine := range strings.Split(verifyFailedErrors[currKey], "\n") {
				_, _ = fmt.Fprintf(stdout, "%s%s\n", strings.Repeat(" ", indentLen*2), currErrLine)
			}
		}
		return fmt.Errorf("conjure verify failed")
	}
	return nil
}

func conjureDefinitionFromParam(param ConjureProjectParam) (spec.ConjureDefinition, error) {
	bytes, err := param.IRProvider.IRBytes()
	if err != nil {
		return spec.ConjureDefinition{}, err
	}
	conjureDefinition, err := conjurego.FromIRBytes(bytes)
	if err != nil {
		return spec.ConjureDefinition{}, err
	}
	return conjureDefinition, nil
}

// cleanupGeneratedFiles deletes Conjure-generated Go files in the specified directory.
// It uses pattern-based deletion to avoid removing hand-written files that may coexist
// with generated code.
//
// A file is considered Conjure-generated if:
// 1. It has a .conjure.go extension, OR
// 2. It's a .go file containing the "// This file was generated by Conjure" header comment
//
// This approach preserves hand-crafted files (e.g., custom serialization logic) while
// cleaning up old generated code.
func cleanupGeneratedFiles(outputDir string) error {
	// If output directory doesn't exist, nothing to clean up
	if _, err := os.Stat(outputDir); os.IsNotExist(err) {
		return nil
	}

	return filepath.Walk(outputDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip directories
		if info.IsDir() {
			return nil
		}

		// Check if file should be deleted
		shouldDelete := false

		// Pattern 1: .conjure.go extension
		if strings.HasSuffix(path, ".conjure.go") {
			shouldDelete = true
		} else if strings.HasSuffix(path, ".go") {
			// Pattern 2: .go file with Conjure generation header
			isGenerated, err := isConjureGeneratedFile(path)
			if err != nil {
				// If we can't determine, err on the side of caution and don't delete
				return nil
			}
			shouldDelete = isGenerated
		}

		// Also clean up extensions.conjure.json files (generated per-IR)
		if filepath.Base(path) == "extensions.conjure.json" {
			shouldDelete = true
		}

		if shouldDelete {
			if err := os.Remove(path); err != nil {
				return errors.Wrapf(err, "failed to delete generated file: %s", path)
			}
		}

		return nil
	})
}

// isConjureGeneratedFile checks if a .go file was generated by Conjure by looking for
// the generation header comment.
func isConjureGeneratedFile(filePath string) (bool, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return false, err
	}
	defer file.Close()

	// Check first few lines for the Conjure generation marker
	scanner := bufio.NewScanner(file)
	lineCount := 0
	maxLinesToCheck := 10 // Only check the first 10 lines

	for scanner.Scan() && lineCount < maxLinesToCheck {
		line := scanner.Text()
		// Look for the Conjure generation comment
		if strings.Contains(line, "This file was generated by Conjure") ||
			strings.Contains(line, "generated by github.com/palantir/conjure-go") {
			return true, nil
		}
		lineCount++
	}

	if err := scanner.Err(); err != nil {
		return false, err
	}

	return false, nil
}
