// Copyright (c) 2018 Palantir Technologies. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package conjureplugin

import (
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/palantir/conjure-go/v6/conjure"
	"github.com/palantir/godel/v2/pkg/dirchecksum"
	"github.com/pkg/errors"
)

// diffOnDisk returns a dirchecksum.ChecksumDiff that represents the diffs between the current on-disk state of files
// in filesToChecksum and the files that would be generated by filesToGenerate. The returned ChecksumsDiff has an entry
// for every path where the checksum or existence state of a file differs and the key is the relative path from
// projectDir to the location of the file that differs.
func diffOnDisk(projectDir string, filesToChecksum []string, filesToGenerate []*conjure.OutputFile) (dirchecksum.ChecksumsDiff, error) {
	originalChecksums, err := checksumOnDiskFiles(projectDir, filesToChecksum)
	if err != nil {
		return dirchecksum.ChecksumsDiff{}, errors.Wrap(err, "failed to compute on-disk checksums")
	}
	newChecksums, err := checksumRenderedFiles(projectDir, filesToGenerate)
	if err != nil {
		return dirchecksum.ChecksumsDiff{}, errors.Wrap(err, "failed to compute generated checksums")
	}

	return newChecksums.Diff(originalChecksums), nil
}

// checksumOnDiskFiles computes the checksums for the provided files based on the content returned by the Render
// function. The returned ChecksumSet has an entry for every file in files that exists and the key is the relative path
// from projectDir to the location to which the file would be rendered.
//
// Returns an error if any path for a file returned by the AbsPath function cannot be made relative to projectDir.
func checksumRenderedFiles(projectDir string, files []*conjure.OutputFile) (dirchecksum.ChecksumSet, error) {
	set := dirchecksum.ChecksumSet{
		RootDir:   projectDir,
		Checksums: map[string]dirchecksum.FileChecksumInfo{},
	}
	for _, file := range files {
		fileAbsPath := file.AbsPath()
		relPath, err := filepath.Rel(projectDir, fileAbsPath)
		if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to make path %s relative to projectDir %s", fileAbsPath, projectDir)
		}
		output, err := file.Render()
		if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to render file %s", fileAbsPath)
		}
		h := sha256.New()
		_, err = h.Write(output)
		if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to checksum generated content for %s", fileAbsPath)
		}
		set.Checksums[relPath] = dirchecksum.FileChecksumInfo{
			Path:           relPath,
			IsDir:          false,
			SHA256checksum: fmt.Sprintf("%x", h.Sum(nil)),
		}
	}
	return set, nil
}

// checksumOnDiskFiles computes the on-disk checksums for the provided files in the provided projectDir. The returned
// ChecksumSet has an entry for every file in filePathsToChecksum that exists and the key is the relative path from
// projectDir to the file.
//
// The files in the filePathsToChecksum slice should either be a relative path within projectDir or an absolute path.
// Returns an error if any path in filePathsToChecksum cannot be made relative to projectDir. Files in
// filePathsToChecksum that do not exist are ignored.
func checksumOnDiskFiles(projectDir string, filePathsToChecksum []string) (dirchecksum.ChecksumSet, error) {
	set := dirchecksum.ChecksumSet{
		RootDir:   projectDir,
		Checksums: map[string]dirchecksum.FileChecksumInfo{},
	}
	for _, file := range filePathsToChecksum {
		// get absolute path for file. If path is already absolute, just cleans it.
		fileAbsPath, err := filepath.Abs(file)
		if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to compute absolute path for %s", file)
		}

		relPath, err := filepath.Rel(projectDir, fileAbsPath)
		if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to make path %s relative to projectDir %s", fileAbsPath, projectDir)
		}

		f, err := os.Open(fileAbsPath)
		if os.IsNotExist(err) {
			// skip nonexistent files
			continue
		} else if err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to open file for checksum %s", fileAbsPath)
		}
		defer func() {
			// file is opened for reading only, so safe to ignore errors on close
			_ = f.Close()
		}()
		h := sha256.New()
		if _, err := io.Copy(h, f); err != nil {
			return dirchecksum.ChecksumSet{}, errors.Wrapf(err, "failed to checksum on-disk content for %s", fileAbsPath)
		}
		set.Checksums[relPath] = dirchecksum.FileChecksumInfo{
			Path:           relPath,
			SHA256checksum: fmt.Sprintf("%x", h.Sum(nil)),
		}
	}
	return set, nil
}
